exports.animals = [
    {
        id:0,
        name:"쭈니",
        comment:"\"천재일우\"",
        fcolor:"하늘색, 파란색",
        fstyle:"엘레강스, 쿨",
        fsong:"K.K.보사노바",
        shabit:"어차피",
        hobby:"노래",
        birthday:"9/29",
        gender:"남자",
        image:require("./images/쭈니.png")
    },
    {
        id:1,
        name:"귀오미",
        comment:"\"좋은일은 망설이지 말자\"",
        fcolor:"노란색, 핑크색",
        fstyle:"큐트 심플",
        fsong:"K.K.발라드",
        shabit:"그럴지도",
        hobby:"자연관찰",
        birthday:"3/7",
        gender:"여자",
        image:require("./images/귀오미.png")
    },
    {
        id:2,
        name:"1호",
        comment:"\"필살기\"",
        fcolor:"빨간색",
        fstyle:"액티브, 심플",
        fsong:"가자! K.K.라이더",
        shabit:"얍",
        hobby:"운동",
        birthday:"8/1",
        gender:"남자",
        image:require("./images/1호.png")
    },
    {
        id:3,
        name:"미애",
        comment:"\"꿈속에서는 영원히 춤출 수 있다\"",
        fcolor:"핑크색, 하얀색",
        fstyle:"큐트, 엘레강스",
        fsong:"K.K.자장가",
        shabit:"어머머",
        hobby:"노래",
        birthday:"3/10",
        gender:"여자",
        image:require("./images/미애.png")
    },
    {
        id:4,
        name:"사이다",
        comment:"\"고양이도 밟으면 꿈틀한다.\"",
        fcolor:"회색, 핑크색",
        fstyle:"심플",
        fsong:"숲 속 생활",
        shabit:"퐁퐁",
        hobby:"노래",
        birthday:"3/27",
        gender:"여자",
        image:require("./images/사이다.png")
    },
    {
        id:5,
        name:"아잠만",
        comment:"\"코흘리개도 어른이 된다\"",
        fcolor:"파란색, 검은색",
        fstyle:"쿨, 심플",
        fsong:"K.K.퓨전",
        shabit:"꽥꽥",
        hobby:"자연관찰",
        birthday:"6/30",
        gender:"남자",
        image:require("./images/아잠만.png")
    },
    {
        id:6,
        name:"잭슨",
        comment:"\"셀프 브랜딩\"",
        fcolor:"검은색, 회색",
        fstyle:"엘레강스, 쿨",
        fsong:"팝K.K.",
        shabit:"우쭐",
        hobby:"자연관찰",
        birthday:"10/1",
        gender:"남자",
        image:require("./images/잭슨.png")
    }
]